In [24]:
import numpy as np
import pandas as pd

In [25]:
df=pd.read_csv('covid_toy.csv')

In [26]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [29]:
from sklearn.compose import ColumnTransformer

In [32]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]) ,['cough']),
    ('tfn3',OneHotEncoder(drop='first',dtype=np.int32),['gender','city'])
    ],remainder='passthrough')

In [35]:
transformer.fit_transform(x_train)

array([[104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  11.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.    

In [36]:
transformer.fit_transform(x_train).shape

(80, 7)

In [37]:
transformer.fit_transform(x_test)

array([[102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [101.,   0.,   0.,   0.,   0.,   1.,  65.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  72.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  71.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [102.,   1.,   0.,   1.,

In [38]:
transformer.fit_transform(x_test).shape

(20, 7)

## without Column Transformer who to solve this problem

### 1st simple Imputer on Fever Column

In [40]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

x_test_fever=si.fit_transform(x_test[['fever']])

In [41]:
x_train_fever.shape

(80, 1)

## 2nd OrdinalEncoding On Cough Column 

In [42]:
oe=OrdinalEncoder(categories=[['Mild','Strong']])

x_train_cough=oe.fit_transform(x_train[['cough']])

x_test_cough=oe.fit_transform(x_test[['cough']])

In [43]:
x_train_cough.shape

(80, 1)

## 3rd OneHotEncoding On Gender and City columns

In [44]:
ohe=OneHotEncoder(drop='first',dtype=np.int32)

x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

In [45]:
x_train_gender_city.shape

(80, 4)

In [47]:
df['gender'].nunique()

2

In [49]:
df['city'].nunique()

4

#### Now Age column

## Extracting Age

In [57]:
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [56]:
x_train_age

array([[51],
       [23],
       [27],
       [49],
       [11],
       [80],
       [38],
       [82],
       [15],
       [65],
       [ 5],
       [60],
       [34],
       [42],
       [34],
       [25],
       [42],
       [38],
       [51],
       [34],
       [79],
       [ 5],
       [50],
       [47],
       [75],
       [20],
       [14],
       [24],
       [68],
       [80],
       [69],
       [ 5],
       [31],
       [17],
       [23],
       [42],
       [22],
       [14],
       [49],
       [46],
       [25],
       [44],
       [ 8],
       [19],
       [73],
       [48],
       [75],
       [71],
       [66],
       [16],
       [84],
       [54],
       [12],
       [24],
       [64],
       [18],
       [83],
       [59],
       [12],
       [73],
       [56],
       [82],
       [19],
       [ 6],
       [49],
       [65],
       [65],
       [47],
       [74],
       [83],
       [55],
       [64],
       [10],
       [26],
       [13],
       [19],
       [16],

## Now Combine this All

In [61]:
x_train_combine=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

x_test_combine=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 2 has 0 dimension(s)